const timezone = [
  { value: 'Alabama', timezone: 'America/Chicago' },
  { value: 'Alaska', timezone: 'America/Anchorage' },
  { value: 'Arizona', timezone: 'America/Phoenix' },
  { value: 'Arkansas', timezone: 'America/Chicago' },
  { value: 'California', timezone: 'America/Los_Angeles' },
  { value: 'Colorado', timezone: 'America/Denver' },
  { value: 'Connecticut', timezone: 'America/New_York' },
  { value: 'Delaware', timezone: 'America/New_York' },
  { value: 'Florida', timezone: 'America/New_York' },
  { value: 'Georgia', timezone: 'America/New_York' },
  { value: 'Hawaii', timezone: 'Pacific/Honolulu' },
  { value: 'Idaho', timezone: 'America/Denver' },
  { value: 'Illinois', timezone: 'America/Chicago' },
  { value: 'Indiana', timezone: 'America/New_York' },
  { value: 'Iowa', timezone: 'America/Chicago' },
  { value: 'Kansas', timezone: 'America/Chicago' },
  { value: 'Kentucky', timezone: 'America/New_York' },
  { value: 'Louisiana', timezone: 'America/Chicago' },
  { value: 'Maine', timezone: 'America/New_York' },
  { value: 'Maryland', timezone: 'America/New_York' },
  { value: 'Massachusetts', timezone: 'America/New_York' },
  { value: 'Michigan', timezone: 'America/New_York' },
  { value: 'Minnesota', timezone: 'America/Chicago' },
  { value: 'Mississippi', timezone: 'America/Chicago' },
  { value: 'Missouri', timezone: 'America/Chicago' },
  { value: 'Montana', timezone: 'America/Denver' },
  { value: 'Nebraska', timezone: 'America/Chicago' },
  { value: 'Nevada', timezone: 'America/Los_Angeles' },
  { value: 'New Hampshire', timezone: 'America/New_York' },
  { value: 'New Jersey', timezone: 'America/New_York' },
  { value: 'New Mexico', timezone: 'America/Denver' },
  { value: 'New York', timezone: 'America/New_York' },
  { value: 'North Carolina', timezone: 'America/New_York' },
  { value: 'North Dakota', timezone: 'America/Chicago' },
  { value: 'Ohio', timezone: 'America/New_York' },
  { value: 'Oklahoma', timezone: 'America/Chicago' },
  { value: 'Oregon', timezone: 'America/Los_Angeles' },
  { value: 'Pennsylvania', timezone: 'America/New_York' },
  { value: 'Rhode Island', timezone: 'America/New_York' },
  { value: 'South Carolina', timezone: 'America/New_York' },
  { value: 'South Dakota', timezone: 'America/Chicago' },
  { value: 'Tennessee', timezone: 'America/Chicago' },
  { value: 'Texas', timezone: 'America/Chicago' },
  { value: 'Utah', timezone: 'America/Denver' },
  { value: 'Vermont', timezone: 'America/New_York' },
  { value: 'Virginia', timezone: 'America/New_York' },
  { value: 'Washington', timezone: 'America/Los_Angeles' },
  { value: 'West Virginia', timezone: 'America/New_York' },
  { value: 'Wisconsin', timezone: 'America/Chicago' },
  { value: 'Wyoming', timezone: 'America/Denver' },
]
export const getTimeZone = (offset: string) => {
  return timezone.find(time => time.value === offset)?.timezone
}
